FROM ruby:3.2.2

# 安装依赖
RUN apt-get update -qq && \
    apt-get install -y nodejs postgresql-client libvips

# 设置工作目录
WORKDIR /app

# 复制 Gemfile
COPY Gemfile Gemfile.lock ./

# 安装 gems
RUN bundle install

# 复制项目文件
COPY . .

# 暴露端口
EXPOSE 3010

# 启动 Rails 服务器
CMD ["rails", "server", "-b", "0.0.0.0", "-p", "3010"] 